### ISSUE TITLE
Rollup simplification

### ISSUE THREAD

**Issue by mpolitzer** [cartesi/machine-emulator#137]
## Context

The rollup system is the bridge that allows a DApp to speak with the blockchain. It was initially designed to receive `input-metadata` and `input` for the blockchain -> DApp direction, and `vouchers` and `notices` on the DApp -> blockchain direction. Recently there is interest in doing different types of outputs[1] from `vouchers` and `notices` and we realized that it would be impractical handling every one of them across the SDK stack. Along those lines, there is also a plan to simplify the input handling by merging the `input-metadata` with `input`[2].

[1] https://github.com/cartesi/rollups-contracts/issues/42
[2] https://github.com/cartesi/rollups-contracts/issues/84

## Possible solutions

The proposed solution is to simplify the rollup, make it handle inputs and outputs as opaque blobs of data and do the encode/decode of blockchain related data in the DApp itself, in userspace.

## Tasks

- [ ] remove `input-metadata`, `notices_hashes` and `voucher_hashes` from the emulator, grpc, defines
  - [ ] https://github.com/cartesi/machine-emulator/pull/136
  - [ ] https://github.com/cartesi/grpc-interfaces/pull/22
  - [ ] https://github.com/cartesi/machine-emulator-defines/pull/7
- [ ] update `src/cartesi-machine.lua` to reflect those changes
  - [ ] `--rollup-advance-state` and `--rollup-inspect-state` calls should be reworked (and simplified if possible)
- [ ] do the rollup memory range operations based on HTIF yield data
- [ ] update `rollup-memory-range.lua` tool to reflect those changes
- [ ] update the linux driver to reflect those changes
  - [ ] https://github.com/cartesi/linux/pull/4
- [ ] update the tools to reflect those changes
  - [ ] https://github.com/cartesi/machine-emulator-tools/pull/24
  - [ ] update tools to use the new library
- [ ] update server-manager to reflect those changes
- [ ] update rom to reflect those changes
  - [ ] https://github.com/cartesi/machine-emulator-rom/pull/13
