### ISSUE TITLE
Deprecate buildroot in favor of the Docker method

### ISSUE THREAD

**Issue by mpolitzer** [cartesi/machine-emulator#139]
Deprecate buildroot in favor of the Dockerfile build method.

## Subtasks

- [x] remove buildroot from SDK
- [x] build a test image in tools
- [x] adjust server-manager tests

**Comment by vfusco** [comment]
closed by #166
