### ISSUE TITLE
Simplify the C API

### ISSUE THREAD

**Issue by edubart** [cartesi/machine-emulator#183]
## Context

Our C API is currently being used to create machine bindings in Lua, Rust, Go and TypeScript languages. Since this, we noticed there are some pain points when creating C bindings in those languages, we could make a refactor to improve it, make it smaller and simpler.

## Subtasks

- [x] Use a JSON string instead of C data structures for loading machines, then deprecate the C config structures. This will make it much easier to bind to other languages, and more proof to mistakes when managing C configs.
- [x] Combine all write/read CSRs methods into a single method using CSR enumerations, this will make the C API much smaller, simplifying the binding work in case someone is not using a binding generator. We can be even more drastic and combine all read/write methods that fits an `uint64` into a single write/read method shared for all registers and CSRs, and use a new enumeration.
- [x] Stop passing double pointers for error messages in all methods, instead all methods should return an error code, and set an error message that can be optionally inspected with `cm_get_last_error_message(machine)`.
- [x] Try to minimize the need of some `cm_delete_*` methods, for example `cm_delete_semantic_version` could be removed by making it always static allocated.
- [x] Some dynamic arrays that have bounded limits could also be replaced with fixed arrays, for example doing this with `cm_merkle_tree_proof` we could remove `cm_delete_merkle_tree_proof` . Similar we could maybe remove `cm_delete_memory_range_config` and `cm_delete_memory_range_descr_array` .

**Comment by tuler** [comment]
Those changes would help as well with the Node.js binding I'm working on. I have ~400 lines (probably badly written) only to handle config.

**Comment by tuler** [comment]
Side node: `cm_reset_uarch` should be called `cm_reset_uarch_halt_flag`, for consistency with other reset methods.

**Comment by diegonehab** [comment]
That’s not what it does. It really resets the entirety of uarch. Including RAM and all other registers.

**Comment by tuler** [comment]
> That’s not what it does. It really resets the entirety of uarch. Including RAM and all other registers.

So documentation should be fixed.
https://github.com/cartesi/machine-emulator/blob/77fb1736e280720921292f9175f0a0217b9804cf/src/machine-c-api.h#L1845

**Comment by diegonehab** [comment]
@perna-cartesi can you take a look?

**Comment by mpernambuco** [comment]
> @mpernambuco can you take a look?

https://github.com/cartesi/machine-emulator/pull/211
