### ISSUE TITLE
Refactor sources to make easier to compile with other build systems

### ISSUE THREAD

**Issue by edubart** [cartesi/machine-emulator#210]
## Context

People may want to bundle libcartesi in other projects and may need to use other build systems, the problem is that we have some generated files that can only be generated in our Makefile build system. We should refactor our sources that is at least `libcartesi` in a way that is very easy to build with other build tools (e.g CMake, node-gyp, etc).

## Subtasks

- [ ] Make `machine-c-version.h` available in the source tarball.
- [ ] Create an `include` directory in `src`, to make easy to just copy include headers.
- [ ] Simplify and make some defines non mandatory to make more difficult to do mistakes when compiling with other build systems
