### ISSUE TITLE
Split and rename iflags_Y, iflags_X, and iflags_H

### ISSUE THREAD

**Issue by diegonehab** [cartesi/machine-emulator#52]
## Context

Currently, we have three bits in CSR `iflags` that play an important role in the way the machine and, in particular, rollups work.
`iflags_H` is set when the machine is halted.
`iflags_Y` is set when the machine has executed a manual yield.
`iflags_X` is set when the machine has just executed an automatic yield.
Whatever code is controlling the emulator via its `machine` interface must check these flags.
Soon, the uarch emulator will need to check `iflags_H` and `iflags_Y` as well (see #51).
It is very inconvenient to read these bits and especially inconvenient to flip them.

## Possible solutions

It would be best to separate these flags into independent CSRs.

As for the names, we could be conservative and change `iflags_Y` to `yield_manual_flag` and `iflags_X` to `yield_automatic_flag`, and `iflags_H` to `halt_flag`. Or we could be more radical and change the `automatic` and `manual` to something more evocative of their use, such as `input`  and `output`.

## Subtasks

- [ ] Pick proper names
- [ ] Allocate space for the new CSRs along with other CSRs
- [ ] Create readers/writers for them in all APIs
- [ ] Create readers/writers for them in state accessors
- [ ] Change all code that uses the old APIs
- [ ] Change the documentation

**Comment by diegonehab** [comment]
Superseded by #257
